name: Update repository data

on:
  workflow_dispatch:
  schedule:
      # every 42 minutes during the day in CA
    - cron: "*/42 0-5,12-23 * * *"

defaults:
  run:
    shell: bash

jobs:
  repo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v2

      - name: Update local repository data
        id: pipeline
        run: ./bin/pipeline.sh repos

      - name: Commit updated data
        id: commit
        env:
          DATA_FILE: ${{ steps.pipeline.outputs.data_file }}
        run: |
          git config user.name "Cal-ITP Bot"
          git config user.email "bot@calitp.org"
          git add ${DATA_FILE}
          timestamp=$(date -u)
          git commit -m "chore(data): updated ${timestamp}" || exit 0
          git push
